const KEY='tipzone_demo_v2';
const defaultData={leagues:['Champions League Qualification','Premier League','La Liga','Serie A','CAF Champions League'],games:[
{id:1,home:'Kairat Almaty',away:'Levski Sofia',league:'Champions League Qualification',date:'2026-08-11',time:'17:00',tip:'Kairat Almaty to Win',odds:'2.50',confidence:'76',status:'pending'},
{id:2,home:'Manchester City',away:'Arsenal',league:'Premier League',date:'2026-08-12',time:'20:00',tip:'Over 2.5 Goals',odds:'1.72',confidence:'81',status:'pending'},
{id:3,home:'Barcelona',away:'Real Madrid',league:'La Liga',date:'2026-08-13',time:'21:00',tip:'Both Teams To Score',odds:'1.65',confidence:'78',status:'pending'}]};
let data=JSON.parse(localStorage.getItem(KEY)||'null')||defaultData;
data.games.forEach(g=>{if(!g.tip)g.tip=g.home+' to Win';if(!g.odds)g.odds='1.80';if(!g.confidence)g.confidence='75'});
let isAdmin=false,currentMatch=null,selections=[];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function renderPredictionGames(){const box=document.getElementById('predictionGames');if(!box)return;box.innerHTML=data.games.length?data.games.map(g=>`<article class="prediction-card" onclick="openMatch(${g.id})"><div class="pc-top"><span class="league-name">${esc(g.league)}</span><span>#${g.id} • ${g.date} ${g.time}</span></div><div class="pc-main"><div><div class="pc-date">${g.date} • ${g.time}</div><div class="pc-teams"><span class="team-name">${esc(g.home)}</span><span class="vs">VS</span><span class="team-name">${esc(g.away)}</span></div></div><div class="pc-prediction"><div class="pc-tip"><small>TIPZONE TIP</small><strong>${esc(g.tip)}</strong></div><div class="pc-odd"><small>ODD</small><b>${esc(g.odds)}</b></div></div></div><div class="pc-bottom"><span>Confidence: <b class="pc-confidence">${g.confidence}%</b></span><span class="pc-select">VIEW ODDS →</span></div></article>`).join(''):'<div class="prediction-empty">No games have been added yet.</div>'}
const markets=[
['Full Time Result',[['1','2.50'],['X','3.15'],['2','3.00']]],
['Double Chance',[['1X','1.39'],['12','1.36'],['X2','1.54']]],
['Both Teams To Score',[['GG','1.92'],['NG','1.78'],['GG 3+','2.65'],['No GG 3+','1.32']]],
['Total Goals',[['0-1','2.70'],['2+','1.40'],['0-2','1.60'],['3+','2.20'],['0-3','1.19'],['4+','4.20'],['5+','9.00'],['6+','22.0'],['7+','60.0'],['1-2','1.87'],['1-3','1.35'],['1-4','1.15']]],
['Half Time Result',[['1','2.95'],['X','2.10'],['2','3.80']]],
['First Team To Score',[['Home','1.55'],['Away','2.25'],['No Goal','8.00']]],
['Over / Under 2.5',[['Over 2.5','1.72'],['Under 2.5','2.05']]]];
function openMatch(id){currentMatch=data.games.find(g=>g.id===id);if(!currentMatch)return;selections=[];document.getElementById('dashboardLeague').textContent=currentMatch.league;document.getElementById('dashboardMatch').innerHTML=`<div class="dashboard-team"><div class="dashboard-time">${currentMatch.date} • ${currentMatch.time}</div><b>${esc(currentMatch.home)}</b></div><div class="dashboard-vs">VS</div><div class="dashboard-team"><div class="dashboard-time">MATCH ODDS</div><b>${esc(currentMatch.away)}</b></div>`;renderDashboardMarkets();renderSelections();showPage('match')}
function renderDashboardMarkets(){document.getElementById('dashboardMarkets').innerHTML=markets.map((m,mi)=>`<div class="market-section"><div class="market-section-title">${m[0]}</div><div class="market-odds ${m[1].length>3?'four':''}">${m[1].map((o,oi)=>`<button class="dashboard-odd" id="odd-${mi}-${oi}" onclick="event.stopPropagation();chooseOdd('${esc(m[0])}','${esc(o[0])}','${o[1]}',${mi},${oi})"><span>${esc(o[0])}</span><b>${o[1]}</b></button>`).join('')}</div></div>`).join('')}
function chooseOdd(market,label,odd,mi,oi){const key=mi+'-'+oi;const idx=selections.findIndex(x=>x.key===key);if(idx>=0)selections.splice(idx,1);else selections.push({key,market,label,odd});const el=document.getElementById('odd-'+key);if(el)el.classList.toggle('selected',idx<0);renderSelections()}
function renderSelections(){document.getElementById('selectionCount').textContent=selections.length;document.getElementById('selectionTotal').textContent=selections.length;document.getElementById('selectionList').innerHTML=selections.length?selections.map((s,i)=>`<div class="selection-item"><div class="sel-market">${esc(s.market)}</div><div class="sel-main"><span>${esc(s.label)}</span><b>${s.odd}</b><button onclick="removeSelection(${i})">×</button></div></div>`).join(''):'<div class="empty-selection">Click an odd to add it.</div>'}
function removeSelection(i){const s=selections[i];selections.splice(i,1);const parts=s.key.split('-');const el=document.getElementById('odd-'+parts[0]+'-'+parts[1]);if(el)el.classList.remove('selected');renderSelections()}
function showPage(n){document.querySelectorAll('.page').forEach(x=>x.classList.add('hidden'));const page=document.getElementById(n+'Page');if(page)page.classList.remove('hidden');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.page===n));if(n==='leagues')renderLeagues();if(n==='results')renderResults()}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function renderLeagues(){document.getElementById('leagueGrid').innerHTML=data.leagues.map(l=>`<div class="league-card"><div>⚽</div><h3>${esc(l)}</h3><p>${data.games.filter(g=>g.league===l).length} scheduled games</p></div>`).join('')}
function renderResults(){document.getElementById('resultsGrid').innerHTML=data.games.map(g=>`<div class="result"><span><b>${esc(g.home)} vs ${esc(g.away)}</b><br><small>${esc(g.league)} · ${g.date} ${g.time}</small></span><strong style="color:#ffcf4b">PENDING</strong></div>`).join('')}
document.getElementById('adminOpen').onclick=()=>isAdmin?showPage('admin'):document.getElementById('loginModal').classList.remove('hidden');
function closeModal(){document.getElementById('loginModal').classList.add('hidden');document.getElementById('loginError').textContent=''}
document.getElementById('loginForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);if(f.get('user')==='admin'&&f.get('pass')==='admin123'){isAdmin=true;closeModal();showPage('admin');renderAdmin()}else document.getElementById('loginError').textContent='Invalid credentials.'}
document.getElementById('logout').onclick=()=>{isAdmin=false;showPage('home')}
document.getElementById('gameForm').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);data.games.push({id:Date.now(),home:f.get('home'),away:f.get('away'),league:f.get('league'),date:f.get('date'),time:f.get('time'),tip:f.get('tip'),odds:f.get('odds'),confidence:f.get('confidence'),status:'pending'});localStorage.setItem(KEY,JSON.stringify(data));e.target.reset();renderAdmin();renderPredictionGames();toast('Game added')}
document.getElementById('leagueForm').onsubmit=e=>{e.preventDefault();let n=new FormData(e.target).get('name').trim();if(!n)return;if(data.leagues.includes(n))return toast('League already exists');data.leagues.push(n);localStorage.setItem(KEY,JSON.stringify(data));e.target.reset();renderAdmin();toast('League added')}
function deleteGame(id){data.games=data.games.filter(g=>g.id!==id);localStorage.setItem(KEY,JSON.stringify(data));renderAdmin();renderPredictionGames()}
function deleteLeague(n){if(data.games.some(g=>g.league===n))return toast('Delete its games first');data.leagues=data.leagues.filter(x=>x!==n);localStorage.setItem(KEY,JSON.stringify(data));renderAdmin()}
function renderAdmin(){document.getElementById('statGames').textContent=data.games.length;document.getElementById('statLeagues').textContent=data.leagues.length;document.getElementById('gameLeague').innerHTML=data.leagues.map(x=>`<option>${esc(x)}</option>`).join('');document.getElementById('adminLeagues').innerHTML=data.leagues.map(x=>`<div class="league-admin"><span>${esc(x)}</span><button class="danger" onclick="deleteLeague('${esc(x)}')">Delete</button></div>`).join('');document.getElementById('adminGames').innerHTML=data.games.map(g=>`<div class="game-admin"><div><b>${esc(g.home)} vs ${esc(g.away)}</b><div class="muted">${esc(g.league)} · ${g.date} ${g.time} · Tip: ${esc(g.tip)} · Odd: ${esc(g.odds)}</div></div><button class="danger" onclick="deleteGame(${g.id})">Delete</button></div>`).join('')}
function demoAction(){toast('Demo only — prediction not placed')}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1700)}
renderPredictionGames();renderAdmin();
